### PR TITLE
Ability to add template variables to a template

### PR DESCRIPTION
**Pull request by Vlczech**
Ability to adjust template variables for transfer to latte template.

### CODE REVIEW

**Comment by uestla** [comment]
For passing custom variables to datagrid template please extend the `createTemplate()` method.

**Comment by Vlczech** [comment]
@uestla: no, this is not a good solution, because you need to rewrite whole parent method, so much of code need to be copy-pasted

**Comment by uestla** [comment]
```php
protected function createTemplate()
{
	$template = parent::createTemplate();
	$template->foo = 'bar';
	return $template;
}
```

**Comment by Vlczech** [comment]
Oh, error, I didn't looking into the code from the tablet (I thought render instead of createTemplate).

**Pull request closed without merging**
